name: dirty
version: 0.1.1
description: Dart Dirty is a persistent, server-side HashMap - a dirt simple nosql DB.
author: Chris Strom <chris@eeecomputes.com>
homepage: https://github.com/eee-c/dart-dirty
dependencies:
  json: ">=0.6.9 <0.6.10"
  unittest: any
